server:
  port: 8080
spring:
  application:
    name: "Zium"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    root: info
    org.ium: trace
    web: debug